services:
  remnawave-node-go:
    build: .
    container_name: remnawave-node-go
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    volumes:
      - xray-geodata:/usr/local/share/xray

volumes:
  xray-geodata:
